#ifndef CONFIG_H_
#define CONFIG_H_

// some macros for configurations (names are self-explanatory)

#define EMULATOR_WINDOW_TITLE   "Chip8 Shadow Self 1970s Edition"
#define CHIP8_MEMORY_SIZE   4096
#define CHIP8_WIDTH     64
#define CHIP8_HEIGHT    32
#define CHIP8_WINDOW_MULTIPLIER 10
#define CHIP8_TOTAL_DATA_REGISTERS 16
#define CHIP8_TOTAL_STACK_DEPTH 16
#define CHIP8_TOTAL_KEYS 16
#define CHIP8_CHARACTER_SET_LOAD_ADDRESS 0x00
#define CHIP8_PROGRAM_LOAD_ADDRESS 0x200
#define CHIP8_DEFAULT_SPRITE_HEIGHT 5

#define BEEP_SAMPLE_RATE 44100
#define BEEP_AMPLITUDE   28000
#define BEEP_FREQUENCY   440

#endif
